### ISSUE TITLE
How to set custom timeout for common AT Command functions?

### ISSUE THREAD

**Issue by TunaBicim** [FreeRTOS/FreeRTOS-Cellular-Interface#100]
Hello all,

How do I set custom timeouts for common functions like Cellular_CommonGetModemInfo?
I see that the send functions use PACKET_REQ_TIMEOUT_MS as the default value.
My modem documentation recommends a longer timeout for some of the common AT commands. 
Since this define doesn't have #ifndef block around it there is no way to redefine it without modifying the Cellular Interface Files.
I wanted to ask if setting a custom timeout is possible before asking for a feature request. 

Thank you,
Tuna Bicim

**Comment by RichardBarry** [comment]
Hi - thanks for your question.  Our preference is to keep all support conversations on the support forum, so there is a single place for users to search for answers.  I would be grateful if you can post your question to https://forums.freertos.org, where we will be happy to reply.
