### ISSUE TITLE
Provide UML interaction diagram for socket send / receive

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/FreeRTOS-Cellular-Interface#129]
These are pretty complex, so a high-level diagram of all interacting components would be beneficial.

**Comment by chinglee-iot** [comment]
The complexity for the socket send/receive is handling the binary data from cellular modem. Cellular interface library relies on the port to indicate the start and the length of the binary data. #139 provides reference port examples can also help user to understand the interaction between cellular modem and cellular interface library.

**Comment by chinglee-iot** [comment]
This PR is merged. We will close this issue first.
