### ISSUE TITLE
Configuration of PKTIO_READ_BUFFER_SIZE

### ISSUE THREAD

**Issue by KeitaKashima** [FreeRTOS/FreeRTOS-Cellular-Interface#169]
Hi, I am using this cellular interface lib, but I faced an issue of below.

The log message showed `No empty space from comm if to handle incoming data, reset all parameter for next incoming data.`

![image](https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/assets/41608629/ae833af8-6028-4d70-8d35-fda1d8b9620f)

After I changed `PKTIO_READ_BUFFER_SIZE` of definition value to 4096, it was solved.

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/blob/aff376d03a4483d7ecb41df6da8401a6ed7e6a38/source/include/private/cellular_common_internal.h#L51

* Question
  *  Is the size of `PKTIO_READ_BUFFER_SIZE` TCP window size?

  It has comment of  `This should be larger than TCP packet size.`, but I think it is window size of TCP. Is my understanding correct?

* Request
  * Is it possible to add (#ifndef PKTIO_READ_BUFFER_SIZE)  to be possible the configuration by the config.h file?

**Comment by chinglee-iot** [comment]
@KeitaKashima
Thank you for reporting this issue.

You're correct in your understanding. The comment should describe the maximum AT command response size, which is typically the TCP socket receive command response packet size. This should be configurable according to the modem specification. We will create a PR to expose this configuration.

**Comment by chinglee-iot** [comment]
@KeitaKashima 
We've created a PR to address this issue #173. It would be great if you can also help to test this PR.

**Comment by KeitaKashima** [comment]
@chinglee-iot 

Thank you for fixing this portion.

I could redefine the `PKTIO_READ_BUFFER_SIZE` in my config.h.
**And it is working fine!**

＜cellular_config.h＞

![image](https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/assets/41608629/66dcd0d6-0f78-40d1-a890-2562a598824d)

The `pketioReadBuf` value is set correctly as I set `4096+1` .

![image](https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/assets/41608629/a9b36617-8f3c-4910-b443-7e18eed58f85)

**Comment by chinglee-iot** [comment]
Thank you for your verification. This issue will be closed. Feel free to reopen this issue or create another one if you have further question.
