### ISSUE TITLE
Cellular_Cleanup does not kill Read Thread

### ISSUE THREAD

**Issue by davideferrario** [FreeRTOS/FreeRTOS-Cellular-Interface#176]
`_Cellular_Init_` function initializes all the library: create mutexes and all the stuff and with `Platform_CreateDetachedThread` function create/start the Read thread.

In case of error in `Cellular_Init` function, this try to cleanup all the allocated resources (`Cellular_ModuleCleanUp` and `_Cellular_LibCleanup` are executed).  `Cellular_ModuleCleanUp` and `_Cellular_LibCleanup` destroy mutexes and all the stuff, except for the thread created by `Platform_CreateDetachedThread`. This can be a problem in case I would like to re-try to run `Cellular_Init` in case of error.

Is it possible to add Read thread destroy in cleanup procedure?

**Comment by ActoryOu** [comment]
Hello, thank you for bringing this to our attention! We will be looking further into this issue as soon as we can, thank you for your patience!

**Comment by chinglee-iot** [comment]
@davideferrario
The thread cleanup can be handled in the Platform_CreateDetachedThread. Please reference our [demo implementation](https://github.com/FreeRTOS/FreeRTOS/blob/36b803e3582a4f22bf6540fb07e9f57f09ee9127/FreeRTOS-Plus/Demo/FreeRTOS_Cellular_Interface_Windows_Simulator/Common/cellular_platform.c#L64).
The created task deletes itself in the wrapper function when it returns from it's thread routine.

**Comment by ActoryOu** [comment]
Hi,
I'm going to close this issue for now since @chinglee-iot has been answered your qeustion.
Feel free to reopen if it's not clear.

Thank you.
