### ISSUE TITLE
Link to demo missing in readme

### ISSUE THREAD

**Issue by boraozgen** [FreeRTOS/FreeRTOS-Cellular-Interface#41]
Congrats on the v1 release!

I noticed that examples/demos are missing from the documentation. I believe [this repo](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-Cellular-Demo ) is supposed to be the demo application for this library. It would be nice to link to it in the readme.

**Comment by muneebahmed10** [comment]
Hi @boraozgen,

I've created #46 to add this to the README and will close this issue when merging. Thank you
