### ISSUE TITLE
Many arguments in LogDebug lines

### ISSUE THREAD

**Issue by mrcamilletti** [FreeRTOS/FreeRTOS-Cellular-Interface#66]
Hi! I'm porting the library to a Nordic nrf52 chip. I've some issues with these lines, where the log command has more arguments than permitted by the SDK log function (the maximum number is 6). Is it possible to divide it in two or more calls ?

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/blob/c4ccd2c09f6bcbd79ce31e773a35f552f8c3f16a/source/cellular_3gpp_api.c#L488

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/blob/c4ccd2c09f6bcbd79ce31e773a35f552f8c3f16a/source/cellular_3gpp_api.c#L1795

**Comment by AniruddhaKanhere** [comment]
Hello @mrcamilletti, thanks for taking the time to report this. We'll take a look and get back to you.

**Comment by chinglee-iot** [comment]
@mrcamilletti, @AniruddhaKanhere 
Thank you the your feedback. I will follow this issue.

**Comment by chinglee-iot** [comment]
@mrcamilletti, @AniruddhaKanhere 
This issue is fixed in #67.
