### ISSUE TITLE
_parseSignalQuality function does not compute RSSI

### ISSUE THREAD

**Issue by jpolonsky-tyc** [FreeRTOS/FreeRTOS-Cellular-Interface#83]
In cellular_hl7802_api.c on line 1080, the function _parseSignalQuality calls _Cellular_ConvertCsqSignalRssi and passes the second argument as "berValue", whereas the function expects raw RSSI as "pRssiValue". 
On line 1066, the first token (which is actually the RSSI value) is deliberately skipped.
In effect, it skips RSSI and miscalculates BER.

**Comment by jpolonsky-tyc** [comment]
I have also noticed that the callback uses _Cellular_ConvertCsqSignalRssi which expects a response received from "AT+CSQ", while the command used for Cellular_GetSignalInfo is "AT+CESQ". The format of RSSI is different in those two messages.

**Comment by chinglee-iot** [comment]
Hi Jpolonsky,

Sorry for late reply. We will look into the question and reply.

**Comment by chinglee-iot** [comment]
@jpolonsky-tyc 
This issue is fixed in this PR #84. Thank you for your feedback.
