### ISSUE TITLE
[Feature Request] Support for byte stream

### ISSUE THREAD

**Issue by es-kaga** [FreeRTOS/FreeRTOS-Cellular-Interface#93]
Hi,
I try to use USECMNG command but this command after sending parameters respond with `\r\n>` sentence which indicates a byte stream mode after that data can be send to the cellular module and final response to the AT comment is received. I try to send this command and data using this library but I cannot find any way how to do this. My cellular module is the SARA R4
Do you think that something like that would be possible using some kind of hack with current library implementation ?

**Comment by chinglee-iot** [comment]
To send byte stream to SARA R4, you need to use API from cellular common layer, for example _Cellular_AtcmdDataSend.

The [cellular_socketsend](https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/blob/8789ade489c02448f0e8e38a06dba96dfe5685a7/modules/sara_r4/cellular_r4_api.c#L642) implementation can be referenced.

**Comment by es-kaga** [comment]
One more question, is there possibility to parse response which is returned by modem after data sent ?

**Comment by chinglee-iot** [comment]
Currently, cellular library doesn't support parse the response after data sent.

**_Cellular_AtcmdDataSend** is consist of **_Cellular_AtcmdRequestTimeoutWithCallbackRaw** and **_Cellular_DataSendWithTimeoutDelayRaw**.
Sending byte stream in **_Cellular_DataSendWithTimeoutDelayRaw** is considered as AT command with **CELLULAR_AT_NO_RESULT** type.
We will discuss to add the response callback for sending byte stream ( sending the data as different AT command type ).

**Comment by tanmoysen** [comment]
We will keep this request in our intake queue, but close this ticket for now. Please feel free to re-open and let us know if you are blocked.
